language: python
python: "3.6"
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: 
  - python test/run.py
  - coveralls run --source=foscambackup test/run.py
after_success:
  - coveralls