language: python
python: "3.6"
install: 
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: 
  - python test/run.py
  - python -m coverage run --source=foscambackup test/run.py
  - python -m coverage report -m
after_success:
  - coveralls