environment:

  matrix:
    - PYTHON: C:\\Python37
    - DISTNAME: foscambackupper
    - DISTFOLDER: "%APPVEYOR_BUILD_FOLDER%\\dist"
    - WORKFOLDER: "%APPVEYOR_BUILD_FOLDER%\\build"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install pyinstaller"
  - cmd: "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

build: off

test_script:
  - cmd: "%PYTHON%\\python.exe -m unittest discover"

after_test:
  - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe main.py --noconfirm --onefile --exclude test --workpath $WORKFOLDER --specpath $WORKFOLDER --distpath $DISTFOLDER --name $DISTNAME"

artifacts:
  - path: "%APPVEYOR_BUILD_FOLDER%\\dist\\%DISTNAME%.exe"

deploy:
  - provider: GitHub
    artifact: "%APPVEYOR_BUILD_FOLDER%\\dist\\%DISTNAME%.exe"
    draft: false
    prerelease: false
    on:
      branch: releases