environment:

  matrix:
    - PYTHON: "C:\\Python37"
    - DISTNAME: "\"foscambackupper\""
    - DISTFOLDER: "%APPVEYOR_BUILD_FOLDER%\\dist"

install:
  - "%PYTHON%\\python.exe -m pip install pyinstaller"
  - "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover"

after_test:
  - "%PYTHON%\\Scripts\\pyinstaller.exe main.py --noconfirm --onefile --exclude test --distpath %DISTFOLDER% --name %DISTNAME%"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: "%APPVEYOR_BUILD_FOLDER%\\dist\\%DISTNAME%.exe"

deploy:
  - provider: GitHub
    artifact: "%APPVEYOR_BUILD_FOLDER%\\dist\\%DISTNAME%.exe"
    draft: false
    prerelease: false
    on:
      branch: releases