- 
  branches:
    only:
      - master

  # Prevent endless build
  skip_tags: true

  skip_branch_with_pr: true
  
  skip_commits:
    message: /no_build/

  environment:
    matrix:
      - PYTHON: C:\\Python37

  init:
      - set DISTNAME=foscambackupper
      - set DISTFOLDER=%APPVEYOR_BUILD_FOLDER%\\dist
      - set WORKFOLDER=%APPVEYOR_BUILD_FOLDER%\\build

  install:
    - cmd: "%PYTHON%\\python.exe -m pip install pyinstaller"
    - cmd: "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

  build: off

  test_script:
    - cmd: "%PYTHON%\\python.exe %APPVEYOR_BUILD_FOLDER%\\test\\run.py"

  after_test:
    - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe main.py --noconfirm --onefile --exclude test --workpath %WORKFOLDER% --specpath %WORKFOLDER% --distpath %DISTFOLDER% --name %DISTNAME%"

  artifacts:
    - path: "\\dist\\%DISTNAME%.exe"
      name: foscambackup

  deploy:
    - provider: GitHub
      release: v$(appveyor_build_version)-stable
      artifact: foscambackup
      draft: false
      prerelease: false
      auth_token:
        secure: yxUm0NN7cTldOGFaMz4Wo/R4YXfthMdtD1bkUxJt2Babll+//tFrynMOUnYxkrOx