environment:
  matrix:
    - PYTHON: C:\\Python37

init:
    - set DISTNAME=foscambackupper
    - set DISTFOLDER=%APPVEYOR_BUILD_FOLDER%\\dist
    - set WORKFOLDER=%APPVEYOR_BUILD_FOLDER%\\build

install:
  - cmd: "%PYTHON%\\python.exe -m pip install pyinstaller"
  - cmd: "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

build: off

test_script:
  - cmd: "%PYTHON%\\python.exe -m unittest discover"

after_test:
  - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe main.py --noconfirm --onefile --exclude test --workpath %WORKFOLDER% --specpath %WORKFOLDER% --distpath %DISTFOLDER% --name %DISTNAME%"

artifacts:
  - path: "\\dist\\%DISTNAME%.exe"

deploy:
  - provider: GitHub
    artifact: "\\dist\\%DISTNAME%.exe"
    draft: false
    prerelease: false
    on:
      branch: releases